version: '3'

networks:
  rts:

services:
  #
  # Vault
  #
  vault:
    hostname: vault
    image: arti.dev.cray.com/third-party-docker-stable-local/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - rts
  vault-kv-enabler:
    build:
      context: .
      dockerfile: vault-kv-enabler.dockerfile
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=secret
    depends_on:
      - vault
    networks:
      - rts

  #
  # Collector
  #
  zookeeper:
    image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rts
  kafka:
    image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-kafka:6.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - rts
  cray-hms-hmcollector:
    image: artifactory.algol60.net/csm-docker/stable/hms-hmcollector:2.12.4
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./configs/kafka_brokers.json:/configs/kafka_brokers.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    ports:
      - 8080:80
      - 8443:443
    networks:
      - rts

  #
  # PMDB
  #
  hms-postgresql:
    image: arti.dev.cray.com/csm-docker-master-local/hms-postgresql:latest
    hostname: hms-postgresql
    command: postgres -c 'max_connections=1000'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - rts
  hms-postgresql-util:
    image: arti.dev.cray.com/sma-docker-master-local/hms-postgresql-util:latest
    depends_on:
      - hms-postgresql
    environment:
      PMDB_HOSTNAME: "hms-postgresql"
    networks:
      - rts
  hms-pmdbd:
    image: arti.dev.cray.com/sma-docker-master-local/hms-pmdbd:latest
    depends_on:
      - hms-postgresql
      - hms-postgresql-util
      - kafka
    environment:
      POSTGRES_HOSTNAME: hms-postgresql
      KAFKA_TOPICS: cray-telemetry-temperature,cray-telemetry-voltage,cray-telemetry-power,cray-telemetry-energy,cray-telemetry-fan,cray-telemetry-pressure,cray-fabric-telemetry,cray-fabric-perf-telemetry,cray-fabric-crit-telemetry,cray-dmtf-resource-event
    networks:
      - rts
  
  grafana:
    image: arti.dev.cray.com/third-party-docker-stable-local/grafana/grafana:7.0.3
    ports:
      - 3000:3000
    networks:
      - rts

  #
  # State Manager
  #
  hmsds-postgres:
    hostname: hmsds-postgres
    image: arti.dev.cray.com/third-party-docker-stable-local/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - "54321:5432"
    networks:
      - rts
  cray-smd-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.30.9
    environment:
      - SMD_DBHOST=hmsds-postgres
      - SMD_DBPORT=5432
    depends_on:
      - hmsds-postgres
    networks:
      - rts
    command: /entrypoint.sh smd-init
  cray-smd:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.30.9
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=secret/hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"
    networks:
      - rts

  #
  # CAPMC
  #
  capmc:
    image: artifactory.algol60.net/csm-docker/stable/cray-capmc:1.25.5
    environment:
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=/configs/namespace
      - CRAY_VAULT_JWT_FILE=/configs/token

      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds

      - HSM_URL=http://cray-smd:27779
    ports:
      - "27777:27777"
    networks:
      - rts
    volumes:
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    depends_on:
      - vault
      - vault-kv-enabler

  #
  # Fake PDUs
  #
  fake-pdus:
    build:
      context: testing/fake_pdu
    ports:
      - "8090:8090"
    networks:
      - rts

  #
  # RTS components for PDUs
  #
  vault-loader:
    build: .
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - JAWS_VAULT_KEYPATH=secret/pdu-creds
    depends_on:
      - vault
      - vault-kv-enabler
    env_file:
      - configs/vault_loader.env
    command: ["vault_loader"]
    networks:
      - rts
  
  redis:
    image: arti.dev.cray.com/third-party-docker-stable-local/redis:5.0-alpine3.12
    hostname: hms-redfish-redis
    ports:
      - "6379:6379"
    networks:
      - rts
  hms-redfish-translation-service:
    build: .
    environment:
      - LOG_LEVEL=INFO
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - VAULT_TOKEN=hms
      - VAULT_ADDR=http://vault:8200
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - HSM_URL=http://cray-smd:27779
      - BACKEND_HELPER=JAWS
      - HTTPS_CERT=configs/rts.crt
      - HTTPS_KEY=configs/rts.key
      - COLLECTOR_URL=http://cray-hms-hmcollector
      - JAWS_VAULT_KEYPATH=secret/pdu-creds
      - HMS_VAULT_KEYPATH=secret/hms-creds
      - CERTIFICATE_VAULT_KEYPATH=secret/pdu-creds/certificates
      - RTS_DNS_PROVIDER=none

    depends_on:
      - redis
      - vault-loader
      - cray-smd
    ports:
      - "8082:8082"
      - "8083:8083"
    networks:
      rts:
        aliases:
          - x0m0-rts
          - x0m1-rts
          - x1000m0-rts
          - x1000m1-rts
          - x1001m0-rts
          - x1001m1-rts
