# MIT License
#
# (C) Copyright [2019-2022,2024] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Dockerfile for running the HMS Redfish Translation Service (RTS) unit tests.

FROM artifactory.algol60.net/docker.io/library/golang:1.23-alpine AS builder-base

RUN set -ex \
    && apk -U upgrade \
    && apk add build-base

RUN go env -w GO111MODULE=auto

FROM builder-base AS builder

# DMTF
ENV SCHEMA_VERSION 2019.1
ENV PRIVILEGE_REGISTRY_VERSION 1.0.4

# Runtime
ENV LOG_LEVEL INFO
ENV CONTRIB_DIR_PREFIX /
ENV SCRIPT_DIR_PREFIX /scripts

# Redis
ENV REDIS_HOSTNAME localhost
ENV REDIS_PORT 6379

# Vault
ENV VAULT_ADDR http://localhost:8200
ENV HMS_VAULT_KEYPATH hms-creds
ENV JAWS_VAULT_KEYPATH pdu-creds

# HSM
ENV HSM_URL http://localhost:27779

# Refish Eventing
ENV COLLECTOR_URL http://hms-hmcollector

# JAWS Backend helper
ENV JAWS_POLLING_ENABLED true
ENV JAWS_POLLING_INTERVAL 10
ENV JAWS_POLLING_WORKERS 30

# Copy support files into the image.
COPY scripts/wait-for.sh /
COPY docker-entrypoint.sh /
COPY contrib ${CONTRIB_DIR_PREFIX}contrib
COPY configs ${CONFIGS_DIR_PREFIX}configs
COPY scripts /scripts
COPY .version /

# Copy source code into the image.
COPY cmd $GOPATH/src/github.com/Cray-HPE/hms-redfish-translation-service/cmd
COPY internal $GOPATH/src/github.com/Cray-HPE/hms-redfish-translation-service/internal
COPY vendor $GOPATH/src/github.com/Cray-HPE/hms-redfish-translation-service/vendor

# Run unit tests...
RUN set -ex \
    && go test -cover -v github.com/Cray-HPE/hms-redfish-translation-service/internal/rfdispatcher/accountservice \
    && go test -cover -v github.com/Cray-HPE/hms-redfish-translation-service/internal/backend_helpers \
    && go test -cover -v github.com/Cray-HPE/hms-redfish-translation-service/internal/rfschema
