name: Build and Publish vault-kv-enabler Docker Image
on:
  - push # Perform a build of the contents from the branch
  - pull_request # Perform a build after merging with the target branch
  - workflow_dispatch
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-image-workflows/.github/workflows/build_and_release_image.yaml@v2
    with:
      image-name: vault-kv-enabler
      docker-build-file: vault-kv-enabler.dockerfile
      docker-build-context: .
      enable-pr-comment: true
    secrets: inherit
